/***************************************/
-- # Exercise 4 - Spatial Clustering
/***************************************/

/***************************************/
-- Which vesseltypes are in the data?
SELECT "VESSELTYPE", "TEXT", COUNT(*) AS COU 
	FROM "AIS_DEMO"."AIS_2017" AS D, "AIS_DEMO"."VESSELTYPE_TEXT" AS C 
	WHERE D."VESSELTYPE" = C."CODE" 
	GROUP BY "VESSELTYPE", "TEXT" ORDER BY COU DESC;
--1025	Tug Tow, Towing Vessel
--1012	Passenger (Inspected)
--1019	Pleasure Craft/Sailing, Recreational
--1004	Cargo, Freight Ship

-- Spatial clustering syntax for hexagons
SELECT ST_CLUSTERID() AS "ID", ST_CLUSTERCELL() AS "SHAPE", COUNT(*) AS C, COUNT(DISTINCT "MMSI") AS "SHIPS" 
	FROM "AIS_DEMO"."AIS_2017"
	GROUP CLUSTER BY "SHAPE_32616" USING HEXAGON Y CELLS 400;

-- Store some of the clusters for visualization
CREATE COLUMN TABLE "AIS_DEMO"."CLUSTER_ALL" (
	"ID" INT PRIMARY KEY, 
	"SHAPE_32616" ST_GEOMETRY(32616), 
	"C" BIGINT, 
	"SHIPS" INT, 
	"SOG" DOUBLE
);
INSERT INTO "AIS_DEMO"."CLUSTER_ALL"
	SELECT ST_CLUSTERID() AS "ID", ST_CLUSTERCELL() AS "SHAPE", COUNT(*) AS C, COUNT(DISTINCT "MMSI") AS "SHIPS", AVG("SOG") AS "SOG" 
		FROM "AIS_DEMO"."AIS_2017"
		GROUP CLUSTER BY "SHAPE_32616" USING HEXAGON Y CELLS 400;


-- same for CARGO vessels
CREATE COLUMN TABLE "AIS_DEMO"."CLUSTER_CARGO" (
	"ID" INT PRIMARY KEY, 
	"SHAPE_32616" ST_GEOMETRY(32616), 
	"C" INT, 
	"SHIPS" INT, 
	"SOG" DOUBLE
);
INSERT INTO "AIS_DEMO"."CLUSTER_CARGO"
	SELECT ST_CLUSTERID() AS "ID", ST_CLUSTERCELL() AS "SHAPE", COUNT(*) AS C, COUNT(DISTINCT "MMSI") AS "SHIPS", AVG("SOG") AS "SOG" 
		FROM "AIS_DEMO"."AIS_2017" WHERE VESSELTYPE = 1004
		GROUP CLUSTER BY "SHAPE_32616" USING HEXAGON Y CELLS 400;


-- same for PASSENGER vessels
CREATE COLUMN TABLE "AIS_DEMO"."CLUSTER_PASSENGER" (
	"ID" INT PRIMARY KEY, 
	"SHAPE_32616" ST_GEOMETRY(32616), 
	"C" BIGINT, 
	"SHIPS" INT, 
	"SOG" DOUBLE
);
INSERT INTO "AIS_DEMO"."CLUSTER_PASSENGER"
	SELECT ST_CLUSTERID() AS "ID", ST_CLUSTERCELL() AS "SHAPE", COUNT(*) AS C, COUNT(DISTINCT "MMSI") AS "SHIPS", AVG("SOG") AS "SOG" 
		FROM "AIS_DEMO"."AIS_2017" WHERE VESSELTYPE = 1012
		GROUP CLUSTER BY "SHAPE_32616" USING HEXAGON Y CELLS 400;
